cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2755102
  brandStrength: 0.2132116
  lightness: 0.2228786
  brandColors:
    - '#141A28'
    - '#F3FFFF'
    - '#C6C281'
    - '#BE6C19'
    - '#6EE5F8'
  rhythmicContrast: 0.7083781
typography_spectrum: 0.3829215
layout_spectrum: 0.4205156
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Reel Stories
